# Generated by Django 2.0.3 on 2019-02-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu_Extras_Sub',
        ),
    ]
