# Generated by Django 2.0.3 on 2019-02-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_menu_extras_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Sub_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraItem', models.CharField(max_length=64)),
                ('smallExtra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largeExtra', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
