# Generated by Django 2.0.3 on 2019-02-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menu_sub_extra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_sub_extra',
            old_name='largeExtra',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='menu_sub_extra',
            old_name='extraItem',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu_sub_extra',
            old_name='smallExtra',
            new_name='small',
        ),
    ]
