# Generated by Django 2.0.3 on 2019-02-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_menu_regular_pizza_idname'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_dinner_platter',
            name='idname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu_pasta',
            name='idname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu_salad',
            name='idname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu_sicilian_pizza',
            name='idname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu_sub',
            name='idname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
