# Generated by Django 2.0.3 on 2019-02-11 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190211_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_username', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
