# Generated by Django 2.0.3 on 2019-02-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190211_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
