# Generated by Django 2.0.3 on 2019-02-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190213_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
