# Generated by Django 2.0.3 on 2019-02-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
