# Generated by Django 2.0.3 on 2019-02-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='smallprice',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
