# Generated by Django 2.0.3 on 2019-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_smallprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='largeprice',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
