# Generated by Django 2.0.3 on 2019-02-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('extra', models.CharField(blank=True, max_length=64, null=True)),
                ('smallprice', models.CharField(blank=True, max_length=64, null=True)),
                ('largeprice', models.CharField(blank=True, max_length=64, null=True)),
                ('price', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
