# Generated by Django 2.0.3 on 2019-02-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_allorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllOrder',
            new_name='All_Order',
        ),
    ]
