# Generated by Django 2.0.3 on 2019-02-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20190220_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
